### ISSUE TITLE
there needs to be consistency with English and Bemba in RemindMi (only portions have been translated)

### ISSUE THREAD

**Issue by mwana** [mwana/mwana#11] opened 2010-05-10 14:05 UTC
I think the "Please notify us when.." is still in English

**Comment by tobiasmcnulty** [comment] 2010-05-11 08:11
duplicate of #9

**Comment by tobiasmcnulty** [comment] 2010-05-12 15:08
83e750e47f92a2c4a1dcf0ac3de51aa07817594f

**Closed as completed by tobiasmcnulty** 2010-05-12 15:08 UTC
Labels: bug
